---
- name: install gui packages
  become: yes
  with_items: "{{ gui_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: configure slim
  become: yes
  template:
    src: slim.conf.j2
    dest: /usr/local/etc/slim.conf

- name: configure i3status
  become: yes
  template:
    src: i3status.conf.j2
    dest: /usr/local/etc/i3status.conf
