- name: install packages
  sudo: yes
  with_items: common_packages
  pkgng:
    name: "{{ item.name }}"
    state: present

- name: create /mnt/usb
  sudo: yes
  file:
    path: /mnt/usb
    owner: root
    group: wheel
    state: directory
