---
- name: install common packages
  become: yes
  with_items: "{{ common_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: link bash
  become: yes
  file:
    src: /usr/local/bin/bash
    dest: /bin/bash
    state: link
