---
- name: ensure user exists
  become: yes
  user:
    name: "{{ user }}"
    shell: /usr/local/bin/fish
    groups: wheel

- name: create user dirs
  become: yes
  become_user: "{{ user }}"
  with_items: "{{ user_directories }}"
  file:
    path: "~{{ user }}/{{ item.path }}"
    state: directory

- name: clone user repositories
  become: yes
  become_user: "{{ user }}"
  with_items: "{{ user_repositories }}"
  git:
    repo: "{{ item.repo }}"
    dest: "~{{ user }}/repos/{{ item.dest }}"
    accept_hostkey: yes
    update: no
    recursive: no

- name: alter .gitmodules
  become: yes
  become_user: "{{ user }}"
  command: "sed -i '.orig' 's;url = git@github.com:;url = https://github.com/;g' ~{{ user }}/repos/dotfiles/.gitmodules"
  args:
    creates: "~{{ user }}/repos/dotfiles/vim/bin/init.sh"
  notify:
    - alter .gitmodules back

- name: get dotfiles submodules
  become: yes
  become_user: "{{ user }}"
  command: git submodule update --init
  args:
    chdir: "~{{ user }}/repos/dotfiles"
    creates: "~{{ user }}/repos/dotfiles/vim/bin/init.sh"

- name: init configuration of programs
  become: yes
  become_user: "{{ user }}"
  command: "~{{ user }}/repos/dotfiles/init.sh"
  args:
    creates: "~{{ user }}/.vim"

- name: configure git
  become: yes
  become_user: "{{ user }}"
  template:
    src: gitconfig.j2
    dest: "~{{ user }}/.gitconfig"

- name: install pyenv
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/yyuu/pyenv"
    update: no
    dest: "~{{ user }}/.pyenv"

- name: link config
  become: yes
  become_user: "{{ user }}"
  with_items: "{{ user_config }}"
  file:
    src: "~{{ user }}/Files/{{ item.name }}"
    dest: "~{{ user }}/{{ item.name }}"
    force: yes
    state: link

- name: setup regular mail checking
  become: yes
  become_user: "{{ user }}"
  cron:
    name: "mail checking"
    job: "~/bin/cron.sh"
    minute: "*"
    user: "{{ user }}"
